import React from "react";
function PrivPol(){
    return(
        <div>
            <h1 className="greeting">Privacy Policy</h1>
        
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla consectetur elit ante, molestie commodo dui varius non. Phasellus quis augue a mauris fermentum tincidunt at vel arcu. Integer at magna vitae arcu tempus pretium. Phasellus viverra luctus varius. Aliquam vulputate mi sit amet tellus tincidunt porttitor in at urna. Praesent sed ante semper, ullamcorper enim ac, efficitur lacus. Etiam quis porttitor est, vitae ullamcorper sem.

Phasellus efficitur cursus ullamcorper. Curabitur leo tellus, elementum ultricies dolor non, porttitor pellentesque massa. Donec et metus sit amet risus facilisis ornare. Nulla facilisi. Nullam nec nulla elit. Donec dui lacus, dapibus id pharetra nec, sodales efficitur nisl. Etiam non ligula ligula. Nunc semper mauris sit amet nibh cursus vestibulum. Praesent ornare dui felis, vel aliquet lacus ultrices gravida. Ut non ornare est, ut malesuada nulla. Aliquam sed tortor dignissim, mattis ex eget, auctor metus.

Donec eros nibh, sodales et luctus a, facilisis et ipsum. Praesent nec ipsum ultricies, hendrerit orci vitae, vestibulum arcu. Curabitur commodo accumsan eleifend. Curabitur vehicula turpis ac nisl imperdiet commodo semper a turpis. Suspendisse potenti. Nunc euismod lacinia tortor, id tempor lacus malesuada non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam diam sapien, facilisis volutpat lectus nec, suscipit rutrum velit. Quisque risus dolor, rhoncus quis vulputate ac, facilisis non augue. Curabitur vitae orci vehicula, fermentum eros et, luctus nunc. Nam ac consectetur purus, id egestas ligula. Cras dolor diam, viverra et nulla at, venenatis commodo nisi. Phasellus condimentum magna quis lorem maximus posuere. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam laoreet turpis at massa iaculis consequat. Sed urna odio, rhoncus et lorem sit amet, imperdiet aliquam magna.

Etiam ac magna imperdiet, bibendum purus eget, laoreet orci. In volutpat tincidunt ultrices. In hac habitasse platea dictumst. Vestibulum sollicitudin posuere bibendum. Maecenas sed massa a ex condimentum tempor non sed elit. Integer laoreet, lacus quis commodo laoreet, tellus lacus ultricies ex, at aliquam sem orci id turpis. Duis vitae tortor ac sem pharetra blandit. Proin nec tempor sapien. Maecenas nec augue vitae metus vulputate semper. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi quis lacus nec eros pellentesque dictum.

Nullam nec turpis non justo pellentesque euismod. Nullam congue tellus et venenatis consectetur. Integer nec feugiat magna. Etiam placerat sapien urna, varius tempor libero sodales eu. Sed a placerat ante. Donec tristique metus risus, in rutrum nulla facilisis ac. Nullam cursus id diam vitae euismod. In cursus rhoncus massa, tincidunt iaculis enim efficitur eu. Maecenas efficitur aliquet ultricies. Donec venenatis convallis eros, eget sodales massa semper vel.

Mauris interdum mauris quis ligula molestie, id dictum ante facilisis. Ut volutpat blandit erat quis vulputate. Fusce sed diam vestibulum, aliquet nunc at, efficitur turpis. Mauris sit amet nibh pulvinar, facilisis turpis vestibulum, suscipit eros. Nunc malesuada sollicitudin ipsum sit amet aliquet. Aliquam at ornare nulla. In auctor lacus lorem, et mattis libero pretium at. Duis auctor metus magna, vel luctus ipsum faucibus sed. Duis elit mi, dictum in imperdiet sit amet, imperdiet vitae purus. Duis condimentum tortor sed bibendum consectetur.

Fusce finibus placerat suscipit. Etiam enim magna, porta lobortis risus quis, viverra malesuada ligula. Proin suscipit porttitor congue. Donec accumsan, tellus in vulputate pharetra, tellus tellus eleifend elit, a varius enim urna ac ligula. Proin viverra lorem eu est imperdiet, vitae pellentesque est tempor. Donec sit amet pretium sapien. Nam sed orci eu dolor sagittis malesuada. In vel feugiat augue.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum fermentum egestas metus. Morbi luctus leo quis augue egestas, ultricies pharetra ex imperdiet. Integer nec tempor eros. Ut varius non elit sit amet gravida. Nullam nisi mi, egestas sit amet ante eu, condimentum luctus magna. Donec ullamcorper tellus sed tellus euismod fermentum. Curabitur sed imperdiet velit. Pellentesque tortor felis, ornare at lacus ut, pretium lacinia risus. Nulla semper rutrum velit sed posuere. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean eget nisl tellus. Mauris iaculis nunc et laoreet congue.

Pellentesque a lectus hendrerit, feugiat dui ut, dapibus massa. Suspendisse bibendum, mauris vel blandit hendrerit, nisi arcu molestie tellus, a finibus purus arcu cursus lacus. Etiam aliquam ultricies eros id eleifend. Fusce efficitur magna ut imperdiet iaculis. Quisque vel ullamcorper est, non lacinia elit. Cras nec magna lectus. Nulla vehicula libero ut est ultrices, eu tempus elit convallis.

Praesent aliquam vestibulum rhoncus. Quisque euismod felis non consectetur rhoncus. Mauris rhoncus nibh a lacus pharetra tincidunt ac rhoncus nisi. Curabitur tristique augue at nibh feugiat ornare. Donec a est efficitur, gravida dolor a, sagittis ex. Donec a viverra turpis. Nullam finibus facilisis suscipit. In hac habitasse platea dictumst. Suspendisse nibh nisi, varius sed nunc a, cursus congue risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla vitae metus non ante laoreet aliquam ut ut mi. Morbi vitae augue semper, aliquet lacus eget, interdum nisi. Donec neque ligula, placerat et accumsan at, tempor tincidunt sem. Donec sit amet dui a erat sollicitudin viverra.

Cras laoreet justo eu sollicitudin accumsan. Cras tempus nunc nunc, vehicula tincidunt mi feugiat vitae. Duis porttitor metus at erat luctus varius. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris rutrum, nisi at lobortis hendrerit, nunc leo lacinia ex, a facilisis metus dui eget risus. Ut finibus tempor vestibulum. Mauris ultrices, massa in egestas ultrices, est nulla sagittis urna, id aliquet augue nulla in velit. Cras non lacus molestie, rutrum tortor sit amet, dapibus nunc. Sed eros eros, tristique hendrerit dignissim in, efficitur vel risus. Quisque quis aliquet magna, at consectetur velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse sit amet felis et nibh ultrices vulputate sed eget metus. Aliquam sodales leo non tempor accumsan. Sed non turpis imperdiet, scelerisque lectus vitae, commodo ante. Quisque a quam eget massa aliquam ullamcorper.

Suspendisse potenti. Nullam sagittis elit eget tempus dapibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacus sem, egestas a rutrum quis, elementum eget lectus. Nullam leo mi, sodales eget rhoncus vitae, tristique vitae nunc. Fusce eget elementum metus, vel lacinia risus. In dapibus nulla et nisi tristique, eget faucibus magna blandit. Sed sed consectetur purus. Donec vel vulputate mi. Nullam eleifend at est quis maximus. Quisque at finibus risus. Nulla condimentum facilisis tortor nec dictum. Maecenas justo massa, convallis id sem quis, fermentum sodales ante. Pellentesque viverra viverra purus, at pretium diam.

Morbi cursus nisl magna, sed euismod massa congue vel. Praesent in mi sed massa vestibulum porttitor. Etiam porta odio et tellus dictum, ac venenatis lacus vulputate. Praesent commodo ultricies malesuada. Phasellus feugiat quam sit amet nibh rhoncus bibendum. Quisque id tellus vitae nulla tempor egestas. Phasellus sed eros rhoncus leo pellentesque efficitur. Integer vehicula sapien in velit tempor iaculis. Nam pulvinar sed nisi quis ullamcorper. Phasellus lacus felis, viverra eget semper nec, imperdiet in odio. Vestibulum aliquam erat eu placerat scelerisque. Quisque faucibus massa sed dui tincidunt, vel pellentesque neque aliquam. In rhoncus laoreet convallis.

Suspendisse fermentum elit et nulla efficitur consectetur. Cras iaculis magna non luctus eleifend. Cras ante nulla, vestibulum eget maximus ut, pharetra at enim. Donec a tincidunt sem. Vivamus egestas, sem interdum ultricies convallis, erat eros porttitor ligula, in congue tellus justo nec sapien. Cras a arcu nisl. Etiam semper, lacus ut dapibus pulvinar, felis turpis consectetur nunc, pharetra consequat purus turpis rhoncus mi. Aenean vestibulum nunc quam, a ornare velit condimentum eu. Phasellus euismod, est sed molestie dictum, dui risus fermentum augue, sed pharetra tellus arcu a nulla. Maecenas sodales eleifend pulvinar. Nullam lacus sem, tempus vel tempus cursus, ultricies vitae libero. In tristique tempor felis sed lacinia. Aenean eget dui a purus pulvinar ornare. Fusce id elit ut massa elementum vulputate sed nec tortor.

Maecenas et nisl libero. Phasellus malesuada, mauris et fermentum pharetra, orci felis congue quam, at accumsan felis justo sed odio. In varius elit a diam convallis varius. Nunc quis mattis est. Vivamus euismod rutrum est, ut placerat mauris semper non. Nullam vitae efficitur magna. In pulvinar malesuada augue, ut tincidunt dui auctor vel.
          
        </div>
    )
}

export default PrivPol;